source 'http://rubygems.org'

gem 'capybara', '=2.16.0'
gem 'webdriver'
gem 'cucumber'
gem 'parallel_tests'
gem 'rspec', '=3.7.0'
gem 'selenium-webdriver', '=3.7.0'
gem 'site_prism'
gem 'httpclient'
gem 'allure-cucumber'
gem 'activesupport'
